### PR TITLE
Add SheetAble to Archives

### PR DESCRIPTION
**Pull request by vallezw**

### CODE REVIEW

**Comment by ad-si** [comment]
Thanks, but can you please keep the style of the list: 1 short concise sentence 😉

**Comment by vallezw** [comment]
Does it work now @ad-si?

**Comment by ad-si** [comment]
Not quite yet 😅
I extend the contributing guide with more details: https://github.com/ad-si/awesome-sheet-music/blob/master/CONTRIBUTING.md

Thanks for your efforts!

**Comment by ad-si** [comment]
… and cool service btw! 👏
 I subscribed to the blog =)

**Comment by vallezw** [comment]
Haha, thanks. It should be all fine now @ad-si. Tell me if there's still anything wrong.

**Comment by ad-si** [comment]
Well, not quite, buy I'm also very pedantic about details, so nevermind, I fixed it myself …

- music x 2, sheet x 2, organize x 2 … let's just say the information density was not optimal here 😝
- It's not an archive, since it doesn't host any sheet music. It's a software library to build your own archive.
- The description text line was wider than 80 characters
- You included the link in the list item itself

**Comment by vallezw** [comment]
Oh yeah sorry about that I wasn't sure where to put it exactly.  However, thanks for writing it for me looks good!

**Pull request merged**
